### ISSUE TITLE
Latest Master Build Not Successful

### ISSUE THREAD

**Issue by wumiaont** [sonic-net/sonic-buildimage#19235]
#### Description
When building the recent sonic-buildimage master, it failed on p4lang. Followings are errors from build output. It is introduced by this commit:
https://github.com/sonic-net/sonic-buildimage/pull/18762/

============================================================================
Testsuite summary for PI-proto 0.1
============================================================================
# TOTAL: 13
# PASS:  10
# SKIP:  0
# XFAIL: 0
# FAIL:  3
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
============================================================================
make[8]: *** [Makefile:1045: test-suite.log] Error 1
make[8]: Leaving directory '/sonic/src/p4lang/p4lang-pi-0.1.0/proto/tests'
make[7]: *** [Makefile:1153: check-TESTS] Error 2
make[7]: Leaving directory '/sonic/src/p4lang/p4lang-pi-0.1.0/proto/tests'
make[6]: *** [Makefile:1310: check-am] Error 2
make[6]: Leaving directory '/sonic/src/p4lang/p4lang-pi-0.1.0/proto/tests'
make[5]: *** [Makefile:1697: check-recursive] Error 1
make[5]: Leaving directory '/sonic/src/p4lang/p4lang-pi-0.1.0/proto'
make[4]: *** [Makefile:1994: check] Error 2
make[4]: Leaving directory '/sonic/src/p4lang/p4lang-pi-0.1.0/proto'
make[3]: *** [Makefile:456: check-recursive] Error 1
make[3]: Leaving directory '/sonic/src/p4lang/p4lang-pi-0.1.0'
dh_auto_test: error: make -j16 check "TESTSUITEFLAGS=-j16 --verbose" VERBOSE=1 returned exit code 2
make[2]: *** [debian/rules:16: binary] Error 25
make[2]: Leaving directory '/sonic/src/p4lang/p4lang-pi-0.1.0'
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
make[1]: *** [Makefile:9: /sonic/target/debs/bookworm/p4lang-pi_0.1.0-15_amd64.deb] Error 2
make[1]: Leaving directory '/sonic/src/p4lang'
[  FAIL LOG END  ] [ target/debs/bookworm/p4lang-pi_0.1.0-15_amd64.deb ]
make: *** [slave.mk:735: target/debs/bookworm/p4lang-pi_0.1.0-15_amd64.deb] Error 1
make[1]: Leaving directory '/home/wumiao/github/sonic-buildimage'

#### Steps to reproduce the issue:
Just follow the build steps for sonic-buildimage and it will fail.

#### Describe the results you received:
Cannot build master

**Comment by Ilayarani-git** [comment]
I am also facing the same issue. Any fix available for this issue?

**Comment by wumiaont** [comment]
Revert https://github.com/sonic-net/sonic-buildimage/pull/18762 can help to resolve the issue.

**Comment by Ilayarani-git** [comment]
After reverting the changes, build was successful. Thanks for your inputs.

**Comment by prabhataravind** [comment]
@Ilayarani-git Is this issue resolved now? If not, please try on the latest master image. We don't see build issues on master. What is the command you are using to build?

**Comment by Pterosaur** [comment]
Hi @Ilayarani-git , I didn't see this issue on the commit
```
commit 1fba66c5d41a19ce9b02f64cd2091c0783da0a78 (HEAD -> master, origin/master, origin/HEAD)
Author: ganglv <88995770+ganglyu@users.noreply.github.com>
Date:   Tue Jun 18 10:13:58 2024 +0800
```

Are you using a clean building folder or not? I guess if these are some stale files, the build of p4lang may fail.

**Comment by Ilayarani-git** [comment]
@prabhataravind , @Pterosaur 

Thanks for looking into it..

I did not try the latest build . Last build I tried was a week back and it failed with plang error. I reverted https://github.com/sonic-net/sonic-buildimage/pull/18762(git revert 3a84ba8cac38c15d70df14ba428bdca9c4a3a3a6) and build was successful.

These are the commands I used to build.
make init
make configure PLATFORM=vs  
make SONIC_BUILD_JOBS=2 target/sonic-vs.img.gz

**Comment by Pterosaur** [comment]
> @prabhataravind , @Pterosaur
> 
> Thanks for looking into it..
> 
> I did not try the latest build . Last build I tried was a week back and it failed with plang error. I reverted #18762 (git revert [3a84ba8](https://github.com/sonic-net/sonic-buildimage/commit/3a84ba8cac38c15d70df14ba428bdca9c4a3a3a6)) and build was successful.
> 
> These are the commands I used to build. make init make configure PLATFORM=vs make SONIC_BUILD_JOBS=2 target/sonic-vs.img.gz



> @prabhataravind , @Pterosaur
> 
> Thanks for looking into it..
> 
> I did not try the latest build . Last build I tried was a week back and it failed with plang error. I reverted #18762 (git revert [3a84ba8](https://github.com/sonic-net/sonic-buildimage/commit/3a84ba8cac38c15d70df14ba428bdca9c4a3a3a6)) and build was successful.
> 
> These are the commands I used to build. make init make configure PLATFORM=vs make SONIC_BUILD_JOBS=2 target/sonic-vs.img.gz

Thanks for your commands. I guess the build of p4lang may has some issues with multiple BUILD JOBS. I will confirm it.

**Comment by wumiaont** [comment]
I just made a build against latest sonic-buildimage master and still fails. 
5 FAILED TESTS
FAIL test_server_arbitration (exit status: 1)

============================================================================
Testsuite summary for PI-proto 0.1
============================================================================
# TOTAL: 13
# PASS:  10
# SKIP:  0
# XFAIL: 0
# FAIL:  3
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
============================================================================
make[8]: *** [Makefile:1045: test-suite.log] Error 1
make[8]: Leaving directory '/sonic/src/p4lang/p4lang-pi-0.1.0/proto/tests'
make[7]: *** [Makefile:1153: check-TESTS] Error 2
make[7]: Leaving directory '/sonic/src/p4lang/p4lang-pi-0.1.0/proto/tests'
make[6]: *** [Makefile:1310: check-am] Error 2
make[6]: Leaving directory '/sonic/src/p4lang/p4lang-pi-0.1.0/proto/tests'
make[5]: *** [Makefile:1697: check-recursive] Error 1
make[5]: Leaving directory '/sonic/src/p4lang/p4lang-pi-0.1.0/proto'
make[4]: *** [Makefile:1994: check] Error 2
make[4]: Leaving directory '/sonic/src/p4lang/p4lang-pi-0.1.0/proto'
make[3]: *** [Makefile:456: check-recursive] Error 1
make[3]: Leaving directory '/sonic/src/p4lang/p4lang-pi-0.1.0'
dh_auto_test: error: make -j12 check "TESTSUITEFLAGS=-j12 --verbose" VERBOSE=1 returned exit code 2
make[2]: *** [debian/rules:16: binary] Error 25
make[2]: Leaving directory '/sonic/src/p4lang/p4lang-pi-0.1.0'
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
make[1]: *** [Makefile:9: /sonic/target/debs/bookworm/p4lang-pi_0.1.0-15_amd64.deb] Error 2
make[1]: Leaving directory '/sonic/src/p4lang'
[  FAIL LOG END  ] [ target/debs/bookworm/p4lang-pi_0.1.0-15_amd64.deb ]
make: *** [slave.mk:735: target/debs/bookworm/p4lang-pi_0.1.0-15_amd64.deb] Error 1
make[1]: *** [Makefile.work:600: all] Error 2
make[1]: Leaving directory '/home/wumiao/github/sonic-buildimage'
make: *** [Makefile:47: all] Error 2

**Comment by wumiaont** [comment]
Command I used for the build:
  967  git clone https://github.com/sonic-net/sonic-buildimage.git
  968  sudo modprobe overlay
  969  cd sonic-buildimage/
  970  make init
  971  make configure PLATFORM=vs
  972  make SONIC_BUILD_JOBS=1 all

**Comment by wumiaont** [comment]
wumiao@wfwumiao:~/github/sonic-buildimage$ git pull
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 28 (delta 7), reused 9 (delta 6), pack-reused 0
Unpacking objects: 100% (28/28), 38.10 KiB | 470.00 KiB/s, done.
From https://github.com/sonic-net/sonic-buildimage
   48ec8cdfe..ace1e5b0e  202311     -> origin/202311
Already up to date.
wumiao@wfwumiao:~/github/sonic-buildimage$ git branch
* master

**Comment by Pterosaur** [comment]
> Command I used for the build: 967 git clone https://github.com/sonic-net/sonic-buildimage.git 968 sudo modprobe overlay 969 cd sonic-buildimage/ 970 make init 971 make configure PLATFORM=vs 972 make SONIC_BUILD_JOBS=1 all

These commands are available in my environment, Could you try to remove your slave image?
```
docker rmi $(docker images | grep slave | awk '{print $3}')
```

**Comment by harjotsinghpawra** [comment]
Hi , i am trying to build 202411 and still seeing this issue any fix so far ?

**Comment by Pterosaur** [comment]
> Hi , i am trying to build 202411 and still seeing this issue any fix so far ?

Hi, Could you please try to cleanup the slave containers via `docker rmi $(docker images | grep slave | awk '{print $3}')` and git clone a  new folder.

**Comment by AnantKishorSharma** [comment]
Hitting the same issue on master

hash used
``
commit 6e37b4bae186e647f957153edbf10133718ac203 (HEAD -> palc/dhcp4relay, origin/palc/dhcp4relay)
Author: Feng-msft <fenpan@microsoft.com>
Date:   Wed Feb 12 22:41:43 2025 +1100

    create bmp container per_namespace for multi-asic (#21712)
```

Error(exactly same failures reported by others)
```
make[7]: Leaving directory '/sonic/src/p4lang/p4lang-pi-0.1.0/proto/tests'
make  check-TESTS
make[7]: Entering directory '/sonic/src/p4lang/p4lang-pi-0.1.0/proto/tests'
make[8]: Entering directory '/sonic/src/p4lang/p4lang-pi-0.1.0/proto/tests'
PASS: test_p4info_convert
PASS: test_proto_fe_bytestrings
PASS: test_proto_fe_set_pipeline_config
PASS: test_pi_server
FAIL: test_server_gnmi
FAIL: test_server_no_pipeline_config
PASS: test_proto_fe_watch_port_enforcer
PASS: test_proto_fe_access_arbitration
FAIL: test_server_arbitration
PASS: test_proto_fe_packet_io
PASS: test_proto_fe_digest
PASS: test_task_queue
PASS: test_proto_fe
========================================
   PI-proto 0.1: tests/test-suite.log
========================================

# TOTAL: 13
# PASS:  10
# SKIP:  0
# XFAIL: 0
# FAIL:  3
# XPASS: 0
# ERROR: 0

```

tried below:
1. the cmd suggested "docker rmi $(docker images | grep slave | awk '{print $3}')", manually force stop/rm containers/images. After everything was clean tried again and still same failures were seen.
2. with single build job

Any other ideas except reverting https://github.com/sonic-net/sonic-buildimage/pull/18762 ?

**Comment by Pterosaur** [comment]
> Hitting the same issue on master
> 
> hash used
> 
> ```
> commit 6e37b4bae186e647f957153edbf10133718ac203 (HEAD -> palc/dhcp4relay, origin/palc/dhcp4relay)
> Author: Feng-msft <fenpan@microsoft.com>
> Date:   Wed Feb 12 22:41:43 2025 +1100
> 
>     create bmp container per_namespace for multi-asic (#21712)
> ```
> 
> Error(same as reported by others)
> 
> ```
> make[7]: Leaving directory '/sonic/src/p4lang/p4lang-pi-0.1.0/proto/tests'
> make  check-TESTS
> make[7]: Entering directory '/sonic/src/p4lang/p4lang-pi-0.1.0/proto/tests'
> make[8]: Entering directory '/sonic/src/p4lang/p4lang-pi-0.1.0/proto/tests'
> PASS: test_p4info_convert
> PASS: test_proto_fe_bytestrings
> PASS: test_proto_fe_set_pipeline_config
> PASS: test_pi_server
> FAIL: test_server_gnmi
> FAIL: test_server_no_pipeline_config
> PASS: test_proto_fe_watch_port_enforcer
> PASS: test_proto_fe_access_arbitration
> FAIL: test_server_arbitration
> PASS: test_proto_fe_packet_io
> PASS: test_proto_fe_digest
> PASS: test_task_queue
> PASS: test_proto_fe
> ========================================
>    PI-proto 0.1: tests/test-suite.log
> ========================================
> 
> # TOTAL: 13
> # PASS:  10
> # SKIP:  0
> # XFAIL: 0
> # FAIL:  3
> # XPASS: 0
> # ERROR: 0
> ....
> ....
> [  FAILED  ] TestArbitration.SingleThreadedClient (373 ms)
> [----------] 5 tests from TestArbitration (401 ms total)
> 
> [----------] Global test environment tear-down
> [==========] 5 tests from 1 test suite ran. (403 ms total)
> [  PASSED  ] 0 tests.
> [  FAILED  ] 5 tests, listed below:
> [  FAILED  ] TestArbitration.WriteNoPrimary
> [  FAILED  ] TestArbitration.DuplicateElectionId
> [  FAILED  ] TestArbitration.WriteAndPacketInAndPacketOut
> [  FAILED  ] TestArbitration.MaxConnections
> [  FAILED  ] TestArbitration.SingleThreadedClient
> 
>  5 FAILED TESTS
> FAIL test_server_arbitration (exit status: 1)
> 
> ============================================================================
> Testsuite summary for PI-proto 0.1
> ============================================================================
> # TOTAL: 13
> # PASS:  10
> # SKIP:  0
> # XFAIL: 0
> # FAIL:  3
> # XPASS: 0
> # ERROR: 0
> ============================================================================
> ```
> 
> tried below:
> 
> 1. the cmd suggested "docker rmi $(docker images | grep slave | awk '{print $3}')", manually force stop/rm containers/images. After everything was clean tried again and still same failures were seen.
> 2. with single build job
> 
> Is reverting [#18762](https://github.com/sonic-net/sonic-buildimage/pull/18762) the only solution to this?

@AnantKishorSharma What's your building command? I can have a try.

**Comment by AnantKishorSharma** [comment]
> > Hitting the same issue on master
> > hash used
> > ```
> > commit 6e37b4bae186e647f957153edbf10133718ac203 (HEAD -> palc/dhcp4relay, origin/palc/dhcp4relay)
> > Author: Feng-msft <fenpan@microsoft.com>
> > Date:   Wed Feb 12 22:41:43 2025 +1100
> > 
> >     create bmp container per_namespace for multi-asic (#21712)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Error(same as reported by others)
> > ```
> > make[7]: Leaving directory '/sonic/src/p4lang/p4lang-pi-0.1.0/proto/tests'
> > make  check-TESTS
> > make[7]: Entering directory '/sonic/src/p4lang/p4lang-pi-0.1.0/proto/tests'
> > make[8]: Entering directory '/sonic/src/p4lang/p4lang-pi-0.1.0/proto/tests'
> > PASS: test_p4info_convert
> > PASS: test_proto_fe_bytestrings
> > PASS: test_proto_fe_set_pipeline_config
> > PASS: test_pi_server
> > FAIL: test_server_gnmi
> > FAIL: test_server_no_pipeline_config
> > PASS: test_proto_fe_watch_port_enforcer
> > PASS: test_proto_fe_access_arbitration
> > FAIL: test_server_arbitration
> > PASS: test_proto_fe_packet_io
> > PASS: test_proto_fe_digest
> > PASS: test_task_queue
> > PASS: test_proto_fe
> > ========================================
> >    PI-proto 0.1: tests/test-suite.log
> > ========================================
> > 
> > # TOTAL: 13
> > # PASS:  10
> > # SKIP:  0
> > # XFAIL: 0
> > # FAIL:  3
> > # XPASS: 0
> > # ERROR: 0
> > ....
> > ....
> > [  FAILED  ] TestArbitration.SingleThreadedClient (373 ms)
> > [----------] 5 tests from TestArbitration (401 ms total)
> > 
> > [----------] Global test environment tear-down
> > [==========] 5 tests from 1 test suite ran. (403 ms total)
> > [  PASSED  ] 0 tests.
> > [  FAILED  ] 5 tests, listed below:
> > [  FAILED  ] TestArbitration.WriteNoPrimary
> > [  FAILED  ] TestArbitration.DuplicateElectionId
> > [  FAILED  ] TestArbitration.WriteAndPacketInAndPacketOut
> > [  FAILED  ] TestArbitration.MaxConnections
> > [  FAILED  ] TestArbitration.SingleThreadedClient
> > 
> >  5 FAILED TESTS
> > FAIL test_server_arbitration (exit status: 1)
> > 
> > ============================================================================
> > Testsuite summary for PI-proto 0.1
> > ============================================================================
> > # TOTAL: 13
> > # PASS:  10
> > # SKIP:  0
> > # XFAIL: 0
> > # FAIL:  3
> > # XPASS: 0
> > # ERROR: 0
> > ============================================================================
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > tried below:
> > 
> > 1. the cmd suggested "docker rmi $(docker images | grep slave | awk '{print $3}')", manually force stop/rm containers/images. After everything was clean tried again and still same failures were seen.
> > 2. with single build job
> > 
> > Is reverting [#18762](https://github.com/sonic-net/sonic-buildimage/pull/18762) the only solution to this?
> 
> [@AnantKishorSharma](https://github.com/AnantKishorSharma) What's your building command? I can have a try.

Hi @Pterosaur ,
Commands used are exactly the same as listed in sonic-buildimage page.
make init
make configure PLATFORM=vs
make SONIC_BUILD_JOBS=4 all

1. Also tried with 1 build job.
2. tried only the failing target separately target/debs/bookworm/p4lang-pi_0.1.0-15_amd64.deb

**Comment by jon-nokia** [comment]
This is still an issue for me on latest 131a4a8b59.  I get exact same error

```

PASS: test_pi_server
PASS: test_proto_fe_watch_port_enforcer
PASS: test_proto_fe_access_arbitration
PASS: test_proto_fe_packet_io
PASS: test_proto_fe_digest
PASS: test_task_queue
FAIL: test_server_gnmi
PASS: test_proto_fe
FAIL: test_server_no_pipeline_config
FAIL: test_server_arbitration
========================================
   PI-proto 0.1: tests/test-suite.log
========================================

# TOTAL: 13
# PASS:  10
# SKIP:  0
# XFAIL: 0
# FAIL:  3
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test_server_no_pipeline_config
====================================

[==========] Running 3 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 3 tests from TestNoForwardingPipeline
Server listening on [::]:0
[ RUN      ] TestNoForwardingPipeline.Write
server/test_no_pipeline_config.cpp:91: Failure
Expected equality of these values:
  StatusCode::FAILED_PRECONDITION
    Which is: 9
  status.error_code()
    Which is: 14
server/test_no_pipeline_config.cpp:68: Failure
Value of: status.ok()
  Actual: false
Expected: true
[  FAILED  ] TestNoForwardingPipeline.Write (3165 ms)
[ RUN      ] TestNoForwardingPipeline.Read
server/test_no_pipeline_config.cpp:104: Failure
Expected equality of these values:
  StatusCode::FAILED_PRECONDITION
    Which is: 9
  status.error_code()
    Which is: 14

```

**Comment by jon-nokia** [comment]
I tried reducing jobs to 1, (SONIC_CONFIG_MAKE_JOBS=1) but that didn't work.    I further investigated the `StatusCode::FAILED_PRECONDITION` and note that error_code 14 is UNAVAILABLE

```
  // The service is currently unavailable.  This is most likely a
  // transient condition, which can be corrected by retrying with
  // a backoff.
  //
  // See the guidelines above for deciding between `FAILED_PRECONDITION`,
  // `ABORTED`, and `UNAVAILABLE`.
  //
  // HTTP Mapping: 503 Service Unavailable
  UNAVAILABLE = 14;
```
So, I think some timing issue in perhaps not waiting long enough for the server to start?

Anyhow, I can now work-around the issue entirely with this change to avoid check, which gives a successful build.

```
diff --git a/src/p4lang/Makefile b/src/p4lang/Makefile
index a896001ba1..eff9d5b72c 100644
--- a/src/p4lang/Makefile
+++ b/src/p4lang/Makefile
@@ -12,7 +12,7 @@ $(addprefix $(DEST)/, $(P4LANG_TARGET)): $(DEST)/% :
 ifeq ($(CROSS_BUILD_ENVIRON), y)
        dpkg-buildpackage -us -uc -b -a$(CONFIGURED_ARCH) -Pcross,nocheck -j$(SONIC_CONFIG_MAKE_JOBS) --admindir $(SONIC_DPKG_ADMINDIR)
 else
-       dpkg-buildpackage -us -uc -b -j$(SONIC_CONFIG_MAKE_JOBS) --admindir $(SONIC_DPKG_ADMINDIR)
+       dpkg-buildpackage -us -uc -b -Pnocheck -j$(SONIC_CONFIG_MAKE_JOBS) --admindir $(SONIC_DPKG_ADMINDIR)
 endif
        popd
        mv $* $(DEST)/

```

**Comment by bradh352** [comment]
I hit this and it is due to HTTP_PROXY/HTTPS_PROXY being set in my environment, the NO_PROXY was set to `localhost,127.0.0.1,::1`

However, I saw in my proxy logs that something was trying to connect to `0.0.0.0` which is non-sensical.

So modifying NO_PROXY to `localhost,127.0.0.1,0.0.0.0,::1` solved it.

This is definitely a bug in p4lang upstream's test cases.
