### ISSUE TITLE
[swssconfig]: Unable to apply large number of config entries in one JSON file

### ISSUE THREAD

**Issue by volodymyrsamotiy** [sonic-net/sonic-buildimage#3849]
**Description**
Unable to apply large number of config entries in one JSON file using ```swssconfig``` tool inside ```swss`` docker container.

**Steps to reproduce the issue:**
1. Prepare JSON file with the 40960 config entries (e.g. VNET route entries were used, but it could any other configuration)
2. Go to ```swss``` container and try to apply prepared config: ```# swssconfig <file>.json```
3. Observe that only about 28000 entries were applied and ```swssconfig``` thrown an exeption 

**Describe the results you received:**
Only about 28000 entries were applied and ```swssconfig``` thrown the following exception:
```
ERR swss#swssconfig: :- main: Exception caught: Unable to connect to redis: Cannot assign requested address
```
Apply procedure was just interrupted by the above exception but all were continue working, nothing crashed and even more config can be applied after the exception.

**Describe the results you expected:**
Expected behavior is to be able to successfully apply large number of config entries (e.g. 40K) using one JSON.

**Additional information you deem important (e.g. issue happens only occasionally):**
Just use any ```master``` based image.

**Comment by volodymyrsamotiy** [comment]
Reopening this issues since it is observed again on latest 201911 images.

**Comment by bingwang-ms** [comment]
Same issue is found in lattest master image SONiC.master.447-bef76b10 when applying a large route config file.
```
Oct 26 05:40:54.180200 str-dx010-acs-4 NOTICE swss#swssconfig: :- main: Loading config from JSON file:/arp_test.json...
Oct 26 05:41:00.540328 str-dx010-acs-4 ERR swss#swssconfig: :- main: Exception caught: Unable to connect to redis: Cannot assign requested address
```
[route_test.zip](https://github.com/Azure/sonic-buildimage/files/5437039/route_test.zip)

**Comment by theasianpianist** [comment]
@volodymyrsamotiy Can you please upload the VNET routes JSON file that you are using?

**Comment by volodymyrsamotiy** [comment]
[vnet.route.json.txt](https://github.com/Azure/sonic-buildimage/files/5523872/vnet.route.json.txt)

@theasianpianist uploaded

**Comment by shi-su** [comment]
I cannot reproduce this issue with the latest master image on a Mellanox sn3800. I tried the `vnet.route.json.txt` shared in the comment and a route file with a million routes. @volodymyrsamotiy Could you please help check if it still happens on your end?

**Comment by liat-grozovik** [comment]
@daall can you please confirm all the fixes are part of 201911? if so, we can validate and test on 201911 and provide info if needed.

**Comment by liat-grozovik** [comment]
The issue was opened on 201911 and IMO is still reproducible with the info provided by Volodymyr.

**Comment by daall** [comment]
Ok, so it seems like there are two things going on here:

1) @bingwang-ms can you please confirm whether or not this issue is present in the master branch? (based on Shi's comment it seems like this has been resolved)

2) @theasianpianist / @shi-su can you please try the repro again against the 201911 image?

@prsunny FYI

**Comment by bingwang-ms** [comment]
I loaded a large config file which contains 10,000 routes for several times on master branch, the issue didn't repro.
I guess it was fixed by https://github.com/Azure/sonic-swss-common/pull/408 ?

**Comment by liat-grozovik** [comment]
@bingwang-ms as stated in the issue description a config of 10k works, also 28K but the max is 28K
As the req is to support 40K you will have a problem and you won't be able to have single config for it but you will need to split the config in chunks. It was verified again with latests of 201911 and the issue is still reproducible.

**Comment by daall** [comment]
Thanks @bingwang-ms for confirming on master branch.

@qiluo-msft could you take a look at this issue on the 201911 branch and see if it makes sense to cherry-pick the PR that @bingwang-ms mentioned into 201911 to fix this?

**Comment by qiluo-msft** [comment]
https://github.com/Azure/sonic-swss-common/pull/408 is not applicable for 201911 branch, because the offensive PR is not there.
